### PR TITLE
(#182) Elevate current linter warnings to errors

### LINKED ISSUE #182: Elevate current linter warnings to errors
Elevate current linter warnings to errors, and prevent commits with linter errors.

Related issue with linter warnings in console #181 would have to be completed before this issue is resolved.

### PR DESCRIPTION
**Pull request by seyilonge-ps**
Closes #182

* Updated eslint config rules from `warn` to `error`
* Removed linter rules from config since `eslint:recommended` is extended making these rules redundant

### CODE REVIEW

**Comment by zoltan-dulac** [comment]
@seyilonge-ps Hey there! It seems that there are ESLinting errors here.  Can you fix and push?

**Comment by zoltan-dulac** [comment]
@seyilonge-ps  Can you review what is wrong with the ESLint scan?  It's failing.

**Review by zoltan-dulac — CHANGES_REQUESTED** [review]
Can you look at the eslint checks? They are failing.

**Comment by seyilonge-ps** [comment]
> Can you look at the eslint checks? They are failing.

I just rebased with the main branch. Lint checks should pass now.

**Review by zoltan-dulac — APPROVED** [review]

**Pull request merged**
